# Generated by Django 4.2.23 on 2025-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually paid', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used', max_length=50),
        ),
    ]
