# Generated by Django 4.2.23 on 2025-08-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('reservations', '0002_reservation_paid_at_reservation_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente registrado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='clients.clientprofile'),
        ),
    ]
