# Generated by Django 4.2.23 on 2025-08-05 18:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0003_reservation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_split_payment',
            field=models.BooleanField(default=False, help_text='Whether this reservation has split payments'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='split_count',
            field=models.IntegerField(default=1, help_text='Number of people splitting the payment', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('payment_token', models.CharField(help_text='Unique token for payment link', max_length=100, unique=True)),
                ('check_in_code', models.CharField(help_text='6-digit code for check-in', max_length=6, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Individual payment amount', max_digits=8)),
                ('payment_method', models.CharField(choices=[('card', 'Tarjeta de crédito/débito'), ('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('pending', 'Pendiente de pago')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=200)),
                ('player_name', models.CharField(blank=True, max_length=200)),
                ('player_email', models.EmailField(blank=True, max_length=254)),
                ('player_phone', models.CharField(blank=True, max_length=20)),
                ('check_in_status', models.CharField(choices=[('pending', 'Pendiente'), ('checked_in', 'Check-in realizado'), ('no_show', 'No se presentó')], default='pending', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('payment_link_accessed_at', models.DateTimeField(blank=True, help_text='When the payment link was first accessed', null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When payment reminder was sent', null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_processed', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_payments', to='reservations.reservation')),
            ],
            options={
                'ordering': ['reservation', 'created_at'],
                'indexes': [models.Index(fields=['payment_token'], name='reservation_payment_0b301f_idx'), models.Index(fields=['check_in_code'], name='reservation_check_i_313f8f_idx'), models.Index(fields=['reservation', 'payment_method'], name='reservation_reserva_be3023_idx')],
            },
        ),
    ]
