# Generated by Django 4.2.23 on 2025-08-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_add_reservation_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='player_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
