# Generated by Django 4.2.23 on 2025-07-28 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.JSONField(default=dict, help_text='Full address as JSON')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_time', models.TimeField(default='07:00')),
                ('closing_time', models.TimeField(default='23:00')),
                ('days_open', models.JSONField(default=list, help_text='List of days open (0=Monday, 6=Sunday)')),
                ('features', models.JSONField(default=list, help_text='List of features: parking, restaurant, shop, etc.')),
                ('settings', models.JSONField(default=dict)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#1E88E5', max_length=7)),
                ('total_courts', models.IntegerField(default=0)),
                ('total_members', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='root.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('maintenance', 'Mantenimiento'), ('event', 'Evento'), ('promotion', 'Promoción')], default='general', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_priority', models.BooleanField(default=False)),
                ('show_on_app', models.BooleanField(default=True)),
                ('show_on_website', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='clubs.club')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='root.organization')),
            ],
            options={
                'ordering': ['-is_priority', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clubs.club')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='root.organization')),
            ],
            options={
                'ordering': ['club', 'weekday'],
                'unique_together': {('club', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('surface_type', models.CharField(choices=[('glass', 'Cristal'), ('wall', 'Pared'), ('mesh', 'Malla'), ('mixed', 'Mixta')], default='glass', max_length=20)),
                ('has_lighting', models.BooleanField(default=True)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_roof', models.BooleanField(default=False)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='clubs.club')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='root.organization')),
            ],
            options={
                'ordering': ['club', 'number'],
                'indexes': [models.Index(fields=['club', 'is_active'], name='clubs_court_club_id_bc42eb_idx'), models.Index(fields=['organization', 'is_active'], name='clubs_court_organiz_2686d8_idx')],
                'unique_together': {('club', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['organization', 'slug'], name='clubs_club_organiz_686d29_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['organization', 'is_active'], name='clubs_club_organiz_affebf_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['club', 'starts_at', 'ends_at'], name='clubs_annou_club_id_f6d036_idx'),
        ),
    ]
